### ISSUE TITLE
How to run on more than 1 node?

### ISSUE THREAD

**Issue by wjlei1990** [SeismicData/pyasdf#15]
Hi Lion,

I was trying to launch the job on more than one node(16 processors per node) on the ornl machine.

So if I do:
```
[lei@rhea12 test_specfem]$ mpiexec -n 17 python process_synthetic.py -p proc_synt_27_60.params.json -f parfile/C200502151442A.proc_synt_50_100.asdf.dirs.json -v
Traceback (most recent call last):
  File "process_synthetic.py", line 6, in <module>
    from proc_util import process_synt
  File "/autofs/nccs-svm1_home1/lei/source_inversion_wf/src/preproc_asdf/proc_util.py", line 1, in <module>
    import obspy
  File "/ccs/home/lei/anaconda2/lib/python2.7/site-packages/obspy/__init__.py", line 36, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/ccs/home/lei/anaconda2/lib/python2.7/site-packages/obspy/core/__init__.py", line 107, in <module>
    from obspy.core.util.attribdict import AttribDict
  File "/ccs/home/lei/anaconda2/lib/python2.7/site-packages/obspy/core/util/__init__.py", line 27, in <module>
    from obspy.core.util.base import (ALL_MODULES, DEFAULT_MODULES,
  File "/ccs/home/lei/anaconda2/lib/python2.7/site-packages/obspy/core/util/base.py", line 28, in <module>
    import numpy as np
  File "/ccs/home/lei/anaconda2/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/ccs/home/lei/anaconda2/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/ccs/home/lei/anaconda2/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/ccs/home/lei/anaconda2/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/ccs/home/lei/anaconda2/lib/python2.7/site-packages/numpy/core/__init__.py", line 15, in <module>
    os.environ.clear()
  File "/ccs/home/lei/anaconda2/lib/python2.7/os.py", line 501, in clear
    unsetenv(key)
OSError: [Errno 22] Invalid argument
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[47909,1],16]
  Exit code:    1
--------------------------------------------------------------------------
```

Do you know what causes that? It seems numpy is not happy with this :)

**Comment by krischer** [comment]
I feel like we already had this problem and it was not related to pyasdf. Can you try the following:

```python
from mpi4py import MPI
import numpy
```

and run it on 17 cores? I think we concluded last time (cannot find the conversation right now) that it was an issue with numpy and you have to either take it up with your machine's admins or somehow change your numpy installation.

**Comment by wjlei1990** [comment]
Indeed! :)

So forgetful these days :( Get old!
